---
name: Master

on:
  push:
    branches:
      - master

jobs:
  LintAndBuild:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go: [ '1.16.x' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0

      - name: Lint
        uses: reviewdog/action-golangci-lint@v2.0.3
        with:
          github_token: ${{ secrets.github_token }}
          golangci_lint_flags: "--config=.golangci.yml"

      - name: Setup env
        run: |
          echo "GOPATH=$(dirname $GITHUB_WORKSPACE)" >> $GITHUB_ENV
          echo "$(dirname $GITHUB_WORKSPACE)/bin" >> $GITHUB_PATH
          mkdir -p "$(dirname $GITHUB_WORKSPACE)/src/github.com/smutel"
          ln -sf "$GITHUB_WORKSPACE/" "$(dirname $GITHUB_WORKSPACE)/src/github.com/smutel/terraform-provider-netbox"
        shell: bash

      - name: Go installation
        uses: actions/setup-go@v2.1.5
        with:
          go-version: ${{ matrix.go }}

      - name: Go fmt
        run: |
          cd "$(dirname $GITHUB_WORKSPACE)/src/github.com/smutel/terraform-provider-netbox"
          go fmt netbox/*
        shell: bash

      - name: Commit changes
        uses: EndBug/add-and-commit@v7.5.0
        with:
          add: 'netbox'
          author_name: smutel
          default_author: github_actor
          message: 'ci: Go fmt'

      - name: Build
        run: |
          cd "$(dirname $GITHUB_WORKSPACE)/src/github.com/smutel/terraform-provider-netbox"
          make build
        shell: bash
