---
name: PR

on:
  pull_request:

jobs:
  LintAndBuild:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go: [ '1.17.x' ]
    steps:
      - name: Check conventional commits in PR
        uses: Namchee/conventional-pr@v0.10.1
        with:
          access_token: ${{ secrets.github_token }}
          label: "no-conventional-commits"
          close: false
          template: "Thank you for your contribution attempt in this repository!\n\nUnfortunately, this pull request doesn't meet our standards by reason we stated below.\nFor future pull requests, please use conventional commits.\nPlease update the commits in this PR with conventional commits rules."
          strict: false
          report: false

      - name: Checkout
        uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 0

      - name: Lint
        uses: reviewdog/action-golangci-lint@v2.1.3
        with:
          github_token: ${{ secrets.github_token }}
          golangci_lint_flags: "--config=.golangci.yml"
          fail_on_error: true

      - name: Setup env
        run: |
          echo "GOPATH=$(dirname $GITHUB_WORKSPACE)" >> $GITHUB_ENV
          echo "$(dirname $GITHUB_WORKSPACE)/bin" >> $GITHUB_PATH
          mkdir -p "$(dirname $GITHUB_WORKSPACE)/src/github.com/smutel"
          ln -sf "$GITHUB_WORKSPACE/" "$(dirname $GITHUB_WORKSPACE)/src/github.com/smutel/terraform-provider-netbox"
        shell: bash

      - name: Go installation
        uses: actions/setup-go@v3.0.0
        with:
          go-version: ${{ matrix.go }}

      - name: Build
        run: |
          cd "$(dirname $GITHUB_WORKSPACE)/src/github.com/smutel/terraform-provider-netbox"
          make build
        shell: bash
