---
name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  Release:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go: [ '1.16.x' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Unshallow
        run: git fetch --prune --unshallow

      - name: Go installation
        uses: actions/setup-go@v2.1.4
        with:
          go-version: ${{ matrix.go }}

      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v4.0.0
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}

      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1

      - name: Generate CHANGELOG for this version
        run: ./utils/getChangelogRelease CHANGELOG.md ${{ steps.tag.outputs.tag }} > /tmp/RELEASE_CHANGELOG.md

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2.4.1
        with:
          version: latest
          args: release --rm-dist --release-notes=/tmp/RELEASE_CHANGELOG.md
        env:
          GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
